export { default as bankImage } from "./bank.svg";
export { default as spyImage } from "./spy.svg";
export { default as shieldImage } from "./shield.svg";
export { default as blockChainGif } from "./blockchain.gif";
export { default as bitCoinImage } from "./bitcoin.svg";
export { default as bnbImage } from "./bnb.svg";
export { default as usdcImage } from "./usdc.svg";
export { default as dogeImage } from "./doge.svg";
export { default as DTPImage } from "./DTP.png";
